theme: minima
title: The thing that does
author: LlamaPresident
email: llamapresident2@gmail.com
description: > we are going to do something as it happens

# social links
twitter_username: zedyse22
github_username:  llamapresident

show_excerpts: false
